### ISSUE TITLE
write to server characteristic

### ISSUE THREAD

**Issue by MobileLaz** [aritchie/bleserver#1]
is it possible to write to the server's own characteristic or can the server characteristic only be written to from the client? Does data need to be sent from server to client via characteristic broadcast?  Do broadcast and notify properties have to both be set when setting up a server characteristic?  Is the only way to receive a broadcast through characteristic.SubscribeToNotifications()?

**Comment by aritchie** [comment]
Please take a look at the samples and docs before firing off a bunch of questions.  I take the time to write them for this specific reason

Broadcast is used to send data to subscribed client(s).  You only have to have the Notify (or Indicate) property set as shown in the sample.
WhenReadRequest is for when a client is requesting data from the server.  
WhenWriteRequest is when the client is sending data to the server.
If you wish to receive data from a server.Broadcast on a client using Acr.Ble, yes, you have to use characteristic.SubscribeToNotifications()

**Comment by MobileLaz** [comment]
i have looked at your examples but i'm having some issues getting the Read() to work correctly which is why i'm asking these questions.  I'll look at it again though.  Thanks

**Comment by aritchie** [comment]
Make sure you answer the read request on the server.  WhenReadRequest().Subscribe(request => request.Value = <your bytes>).  

Also note that if you are pushing several broadcasts a second on android, it is easy to overwhelm the channel and back up all other requests such as a read

**Comment by MobileLaz** [comment]
i'm able to discover the server and all the characteristics that are setup from the client when the service is first discovered, however, for some reason the client does not see the notifications when broadcasting data.  This is the way i set up the notification characteristic and subscribed to the event

Notify = service.AddCharacteristic
                (
                    BTNotifyGUID,
                    CharacteristicProperties.Indicate | CharacteristicProperties.Notify | CharacteristicProperties.Broadcast,
 GattPermissions.Read | GattPermissions.Write
                );

Notify.Broadcast(Encoding.UTF8.GetBytes(Data));

Notify.SubscribeToNotifications().Subscribe(bytes => { } );

like is said the service characteristic is found on discovery so i know that service is there, however, why doesn't the subscription get called whenever a broadcast is sent?

**Comment by aritchie** [comment]
Subscribe or await the broadcast call and the data will push

**Comment by MobileLaz** [comment]
does the subscription method have to be in a static class or can it be in an instance as long as the instance doesn't go out of scope?
